name: Stress Test com Locust

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # corrige o aviso de Node.js 20

jobs:
  stress-test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependências
        run: pip install locust

      - name: Rodar stress test
        run: |
          locust \
            --headless \
            --users 50 \
            --spawn-rate 5 \
            --run-time 60s \
            --host https://automationexercise.com \
            --csv relatorio \
            --html relatorio.html
        working-directory: ${{ github.workspace }} # garante que os arquivos são salvos no lugar certo

      - name: Listar arquivos gerados # confirma o que foi criado antes de fazer upload
        run: ls -la

      - name: Salvar relatório como artefato
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: relatorio-locust
          path: |
            relatorio.html
            relatorio_stats.csv
            relatorio_failures.csv
          if-no-files-found: warn # 